build:
  image: php:5.6
  commands:
    - php composer.phar install --prefer-source --no-interaction
    - cp .env.testing .env
    - touch database/database.sqlite
    - php artisan migrate
    - vendor/bin/phpunit
