stages:
  - lint
  - build
  - test
  - deploy

lint_phpmd_job:
  image: registry.noprobe.co.uk/coding-standards
  stage: lint
  script:
    - phpmd ./app text .testing/phpmd_ruleset.xml
  tags:
    - docker

lint_phpcs_job:
  image: registry.noprobe.co.uk/coding-standards
  stage: lint
  script:
    - phpcs --standard=psr2 ./app -p --colors --ignore='*/*.blade.php'
  tags:
    - docker

lint_semistandard_job:
  image: registry.noprobe.co.uk/coding-standards
  stage: lint
  script:
    - semistandard
  tags:
    - docker

php_test_job:
  image: registry.noprobe.co.uk/nginx-phpfpm
  stage: test
  script:
    - php composer.phar install
    - cp .env.testing .env
    - touch database/database.sqlite
    - php artisan migrate
  tags:
    - docker

deploy_job:
  stage: deploy
  script:
    - cd $DEPLOY_DIRECTORY && git pull
    - docker exec pipes.noprobe.co.uk php composer.phar install
    - docker exec pipes.noprobe.co.uk php artisan migrate
  only:
    - master
  tags:
    - pipes.noprobe.co.uk

deploy_dev_job:
  stage: deploy
  script:
    - cd $DEVELOPMENT_DEPLOY_DIRECTORY && git pull
    - docker exec dev.pipes.noprobe.co.uk php composer.phar install
    - docker exec dev.pipes.noprobe.co.uk php artisan migrate
  only:
    - development
  tags:
    - dev.pipes.noprobe.co.uk
