stages:
  - test
  - deploy

php_test_job:
  image: registry.noprobe.co.uk/lumen:5.1
  stage: test
  script:
    - php composer.phar install
    - cp .env.testing .env
    - touch database/database.sqlite
    - php artisan migrate
  tags:
    - docker

deploy_job:
  stage: deploy
  script:
    - cd $DEPLOY_DIRECTORY && git pull
    - docker exec lumen php composer.phar install
    - docker exec lumen php artisan migrate
  only:
    - master
  tags:
    - pipes.noprobe.co.uk
