language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
before_install:
  - cp .env.testing .env
  - touch database/database.sqlite
install:
  - php composer.phar install --prefer-source --no-interaction
  - php artisan migrate
script: phpunit
notifications:
  slack: pipes-team:XIqUP7e90C1pFSs4NWQkaQrQ
