php:
  container_name: pipes_php
  image: registry.noprobe.co.uk/nginx-phpfpm:ssh
  ports:
    - "9000:80"
  volumes:
    - .:/var/www
    - .docker/nginx/sites-enabled:/etc/nginx/sites-enabled
  links:
    - mysql:mysql
    - ssh:ssh

mysql:
  container_name: pipes_mysql
  image: registry.noprobe.co.uk/mariadb
  ports:
    - "3309:3306"
  volumes:
    - .docker/db/data:/var/lib/mysql

cron:
  container_name: pipes_cron
  image: registry.noprobe.co.uk/nginx-phpfpm:ssh
  volumes_from:
    - php
  links:
    - mysql:mysql
    - ssh:ssh
  command:
    - "/var/www/scripts/cron.py"

queue_runner_default:
  image: registry.noprobe.co.uk/nginx-phpfpm:ssh
  volumes_from:
    - php
  links:
    - mysql:mysql
    - ssh:ssh
  command: /var/www/scripts/queue-runner.sh default

queue_runner_actions_1:
  image: registry.noprobe.co.uk/nginx-phpfpm:ssh
  volumes_from:
    - php
  links:
    - mysql:mysql
    - ssh:ssh
  command: /var/www/scripts/queue-runner.sh actions

#queue_runner_notifications_1:
#  image: registry.noprobe.co.uk/nginx-phpfpm:ssh
#  volumes_from:
#    - php
#  links:
#    - mysql:mysql
#    - ssh:ssh
#  command: /var/www/scripts/queue-runner.sh notifications

ssh:
  container_name: pipes_ssh
  image: registry.noprobe.co.uk/sshd
