php:
  image: registry.noprobe.co.uk/nginx-phpfpm
  ports:
    - "9000:80"
  volumes:
    - .:/var/www
    - .docker/nginx/sites-enabled:/etc/nginx/sites-enabled
  links:
    - mysql:mysql

mysql:
  image: registry.noprobe.co.uk/mariadb
  ports:
    - "3309:3306"
  volumes:
    - .docker/db/data:/var/lib/mysql

cron:
  image: registry.noprobe.co.uk/nginx-phpfpm
  volumes_from:
    - php
  links:
    - mysql:mysql
  command:
    - "/var/www/scripts/cron.py"

runner:
  image: registry.noprobe.co.uk/pipes-runner
  volumes_from:
    - php
  links:
    - mysql:mysql
